### ISSUE TITLE
Editing files

### ISSUE THREAD

**Issue by brancusi** [xacaxulu/RailsDockerVagrantDevKit#4]
Hi,

Thanks for putting this up.

After running `vagrant up` and `docker-compose up -d`, when I edit project files, I am not seeing updates when I refresh the browser. Only after rebuilding the image do I see the changes.

Is there a way to edit and have the files running in the docker container reflect the changes?

I see the use of `VOLUME`, and I thought that would use the host files, am I missing something here?

Thanks

**Comment by joegesualdo** [comment]
I'm experiencing the same issue.

**Comment by xacaxulu** [comment]
Docker containers are a snapshot in time (or layered filesystems if you will). If you wanted to update the Docker image/container with new code or files, you would necessarily need to rebuild the docker image. Thats docker functionality, not anything to do with the rest of the stack.
